### ISSUE TITLE
Division by zero

### ISSUE THREAD

**Issue by mcs** [vdurmont/etaprinter#1]
In line 164 of the ETAPrinter, itemDurationMillis is often 0 with the consequence of a /zero exception.

Version: Tag 1.0.0 (using Maven)
Runtime: OpenJDK 8 (openjdk-1.8.0.191-1.b12.redhat.windows.x86_64) on Windows 10 Pro

I tried to increase the wait time between two update calls to "every 100 processing units", but without success. 

Edit: Tried the current master which seems to fix the issue. Maybe time for a new release? 👍

**Comment by vdurmont** [comment]
Only 4 years later (sorry for the delay? 🙄), it's fixed in 19039bdbbece8b05ceab2a23757f4e1e8b6872cb and I'm releasing v2.0.0 with the fix on maven central in 29712b2f9f9ff633ca1853c74f8fed90fa1b8136 (should be available in < 2 hours).
